"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import { SessionProvider } from "next-auth/react";
import { ToastContainer, toast } from 'react-toastify';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased light`}
      >
        <div className="min-h-screen bg-pirate-oceanBlue" >
          <ToastContainer />
          <SessionProvider>
            {children}
          </SessionProvider>
          {/* <Footer /> */}
        </div>
      </body>
    </html>
  );
}
